version: "3.9"

services:
  # =======================
  # 1) MongoDB
  # =======================
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - weather_net

  # =======================
  # 2) Mongo Express (opcional mas útil)
  # =======================
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - weather_net
    depends_on:
      - mongo

  # =======================
  # 3) RabbitMQ
  # =======================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # painel web
    networks:
      - weather_net

  # =======================
  # 4) Backend NestJS
  # =======================
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-api
    restart: unless-stopped
    env_file:
      - ./api/.env
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - weather_net
    command: ["npm", "run", "start:prod"]

  # =======================
  # 5) Frontend React/Vite
  # =======================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - "5173:3000"
    networks:
      - weather_net

  # =======================
  # 6) Worker Go
  # =======================
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker-go
    restart: unless-stopped
    env_file:
      - ./worker/.env
    depends_on:
      - rabbitmq
      - api
    networks:
      - weather_net

  # =======================
  # 7) Coletor Python
  # =======================
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: python-collector
    restart: unless-stopped
    env_file:
      - ./collector/.env
    depends_on:
      - rabbitmq
    networks:
      - weather_net

# =======================
# Volumes e Redes
# =======================
volumes:
  mongo_data:

networks:
  weather_net:
    driver: bridge
