version: "3.9"

services:
  api:
    container_name: nest-api
    build: ./api
    ports:
      - "${API_PORT}:3000"
    environment:
      PORT: 3000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${API_JWT_SECRET}
      DEFAULT_ADMIN_EMAIL: ${API_DEFAULT_ADMIN_EMAIL}
      DEFAULT_ADMIN_PASSWORD: ${API_DEFAULT_ADMIN_PASSWORD}
    depends_on:
      - mongo
    networks:
      - weather_net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "3001:80"
    environment:
      VITE_API_URL: "http://localhost:3000"
    networks:
      - weather_net

  collector:
    container_name: python-collector
    build: ./collector
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      QUEUE_NAME: ${QUEUE_NAME}
      WEATHER_API_URL: ${WEATHER_API_URL}
      WEATHER_LAT: ${WEATHER_LAT}
      WEATHER_LON: ${WEATHER_LON}
      WEATHER_PARAMS: ${WEATHER_PARAMS}
      INTERVAL: ${COLLECTOR_INTERVAL}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - weather_net

  worker:
    container_name: worker-go
    build: ./worker
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      API_URL: "http://api:3000"
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started
    networks:
      - weather_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - weather_net

  mongo:
    image: mongo
    networks:
      - weather_net
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - weather_net

volumes:
  mongo_data:

networks:
  weather_net:
